backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"

public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{dev}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
